# Generated by Django 2.2.5 on 2019-11-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='idNumber',
            new_name='idNum',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secretKey',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='eiahb3838ya@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='psw',
            field=models.CharField(default='evan1223', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='publicKey',
            field=models.BinaryField(default=b' '),
            preserve_default=False,
        ),
    ]
