# Generated by Django 2.2.5 on 2019-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_auto_20191101_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publicKey',
            field=models.CharField(max_length=20),
        ),
    ]
