# Generated by Django 2.2.5 on 2019-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractAccount', '0002_contractrelatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='encryptedContext',
            field=models.BinaryField(),
        ),
    ]
