# Generated by Django 2.2.5 on 2019-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_profile_publicaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publicKey',
            field=models.CharField(max_length=64),
        ),
    ]
