# Generated by Django 2.2.5 on 2019-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_auto_20191103_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publicAddress',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='publicKey',
            field=models.CharField(max_length=70),
        ),
    ]
