# Generated by Django 2.2.5 on 2019-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0007_auto_20191103_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publicKey',
            field=models.CharField(max_length=130),
        ),
    ]
