# Generated by Django 2.2.5 on 2019-11-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_auto_20191101_1502'),
        ('contractAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRelatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractHash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractAccount.Contract')),
                ('idNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAccount.Profile')),
            ],
            options={
                'db_table': 'contract_relatives',
            },
        ),
    ]
