# Generated by Django 2.2.5 on 2019-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractAccount', '0003_auto_20191103_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='reveal',
            field=models.BooleanField(default=False),
        ),
    ]
